apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: barriofarma-sites-pvc
  namespace: barriofarma
  labels:
    app.kubernetes.io/name: barriofarma
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard-rwo

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: barriofarma-logs-pvc
  namespace: barriofarma
  labels:
    app.kubernetes.io/name: barriofarma
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard-rwo
